### ISSUE TITLE
Ability for App or Service Provider to Decline the Subscription request

### ISSUE THREAD

**Issue by tfjanjua** [eclipse-tractusx/portal-backend#1140]
### Description
We have apps and service’s subscriptions which we want to “Decline” by App/Service Provider or Admin type of users. Currently we only have Activate and Deactivate Subscription functionality by App/Service Provider type of users.

### Acceptance Criteria

- App/Service Provider or Admin type of users could “Decline” the subscription request, made by the users of same company or another company.
- App/Service Provider or Admin type of users wouldn’t be able to Re-Activate the declined subscription request.
- The declination can only take place after the subscription request and before the activation of the subscription request.
- Subscription request would just simply be removed from the list of subscription requests, after the declination. 
- Frontend may ask for the confirmation of declination before sending request to backend.
- This declination would remove the subscription request but requester (subscriber) would still have the possibility to subscribe the same App/Service from the same, App/Service Details page.
- An email is sent to the requester to confirm the subscription was declined.

### Tasks

- [x] Backend would introduce a new API to Decline the subscription request.
- [x] This new API would be part of both of the entities (App and Service).
- [x] This new API would have same role/right as Activating the App/Service Subscription Request by the Provider or Admin type of users.
- [x] API would just simply delete the record of the subscription request from the database so, there will be no extra data would be existing into the database and there will be no change into the listing of subscription request API.
- [x] API would send the notification email to the requester regarding the declination.

### Corresponding IAM Ticket To Add Role `decline_subscription`

https://github.com/eclipse-tractusx/portal-iam/issues/232

### Test Cases

**Test Case 1**: Verify to Decline a pending subscription request of my own offer

- Lets have 2 companies (e.g. **C1** and **C2**).
- Login with **C1** and navigate to `https://portal.example.com/appReleaseProcess`.
- Release an App (e.g: **A1**) and navigate to `https://portal.example.com/adminboard` and approve it. 
- Logout **C1** and re-login with **C2**
- Navigate to App Marketplace and search for **A1** and subscribe it.
- Logout **C2** and re-login with **C1** and navigate to `https://portal.example.com/appSubscription`
- Search for recent app subscription request from **C2** and Decline it.
- **Result**: Successful

**Test Case 2**: Verify to Decline an already approved subscription request of my own offer

- Lets have 2 companies (e.g. **C1** and **C2**).
- Login with **C1** and navigate to `https://portal.example.com/appReleaseProcess`.
- Release an App (e.g: **A1**) and navigate to `https://portal.example.com/adminboard` and approve it. 
- Logout **C1** and re-login with **C2**
- Navigate to App Marketplace and search for **A1** and subscribe it.
- Logout **C2** and re-login with **C1** and navigate to `https://portal.example.com/appSubscription`
- Search for recent app subscription request from **C2** and try to Decline it.
- **Result**: Error because subscription request has already been Approved.

**Test Case 3**: Verify to Decline an already declined subscription request of my own offer

- Lets have 2 companies (e.g. **C1** and **C2**).
- Login with **C1** and navigate to `https://portal.example.com/appReleaseProcess`.
- Release an App (e.g: **A1**) and navigate to `https://portal.example.com/adminboard` and approve it. 
- Logout **C1** and re-login with **C2**
- Navigate to App Marketplace and search for **A1** and subscribe it.
- Logout **C2** and re-login with **C1** and navigate to `https://portal.example.com/appSubscription`
- Search for recent app subscription request from **C2** and try to Decline it.
- **Result**: Subscription request shouldn't be available for any further action because its already declined.

**Test Case 4**: Verify to Decline a subscription request of someone else's offer

- Lets have 2 companies (e.g. **C1** and **C2**).
- Login with **C1** and navigate to `https://portal.example.com/appReleaseProcess`.
- Release an App (e.g: **A1**) and navigate to `https://portal.example.com/adminboard` and approve it. 
- Logout **C1** and re-login with **C2**
- Navigate to App Marketplace and search for **A1** and subscribe it.
- Logout **C2** and re-login with **C1** and navigate to `https://portal.example.com/appSubscription`
- Search for recent app subscription request from **C2** and try to Decline it.
- **Result**: Subscription request shouldn't be available for any further action because its wouldnt be my own offer's subscription request.
