### ISSUE TITLE
Method Registration Validation "companyDetails"

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-backend#436]
## Summary

With PR #406 a HF got released to fix the companyDataValidation which was identified to be to restricting.
With this ticket the implementation of the correct validation level is getting re-checked and adjusted.

### Details

<img width="895" alt="image" src="https://github.com/eclipse-tractusx/portal-backend/assets/94133633/a546dde3-150e-4005-86cf-ce5b77cd1e93">

Suggested Validation:

- ExternalRegistration
  - BPN duplication to an existing network partner under portal db companies with companies.company_status_id = "ACTIVE" should not exist. Duplication to an PENDING or INACTIVE record is allowed
  - Unique ID duplication to an existing network partner under portal db companies with companies.company_status_id = "ACTIVE" should not exist. Duplication to an PENDING or INACTIVE record is allowed
  - ...
 
- InviteRegistration
  - BPN duplication to an existing network partner under portal db companies with companies.company_status_id = "ACTIVE" should not exist. Duplication to an PENDING or INACTIVE record is allowe
  - Unique ID duplication to an existing network partner under portal db companies with companies.company_status_id = "ACTIVE" should not exist. Duplication to an PENDING or INACTIVE record is allowed

```diff
!!! please note this is a change which impacts the FE quite a lot.  Joint implementation will be needed. Backend can go first; but without an aligned implementation no PR merge possible
```

### Tasks

- [ ] implement the new validation
- [ ] test the validation for the normal registration as well as external registration
- [ ] create pr
- [ ] pr reviewed
- [ ] code deployed to dev
- [ ] successfully tested on dev
- [ ] check documentation update (under assets - developers)

**Comment by evegufy** [comment]
@MaximilianHauer wasn't implemented as part of 24.05, would be great if you could say if it should still be implemented

**Comment by MaximilianHauer** [comment]
@dorkabcox / @ybidois can you evaluate if this is a benefitial change for you ? i dont want to reintroduce something again that is providing negativ effects for you

**Comment by ybidois** [comment]
@MaximilianHauer I wouldn't add more validations for now. Ideally, we would align with BPDM on the exact process to check for BPN duplicates, as they are the ones "owning" the BPNs. We could refine this ticket again first, as part of 25.06.
